spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.186.128:3306/gulimail_pms
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.186.128:8848
    alicloud:
      access-key: LTAI5tNrUWEW2GY8yAoHo5YD
      secret-key: lpDIwy04xVCqSxWuYXpFJL492Tgnjm
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #\u4E3B\u952E\u81EA\u589E
  global-config:
    db-config:
      id-type: auto
      logic-not-delete-value: 0
      logic-delete-value: 1

logging:
  level:
    org.wz.gulimail: debug