
server:
  port: 9000

spring:
  profiles:
    active: dev
  application:
    name: gulimail-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.186.128:3306/gulimail_oms
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.186.128:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #\u4E3B\u952E\u81EA\u589E
  global-config:
    db-config:
      id-type: auto